# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger on every release get created
on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

# Job will run on a ubuntu instance
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      - name: Publish the files to NPM
        run: npm run publish:lib
      # for publishing, npm need authorization. We add the NPM token to the environment which will take care of authorization to publish to the package
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}